version: 2

builds:
  - main: ./cmd/topf
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.version={{.Version}}

archives:
  - formats:
      - tar.gz
    name_template: >-
      {{ .ProjectName }}_{{ .Os }}_{{ .Arch }}

dockers_v2:
  - images:
      - ghcr.io/postfinance/topf
    tags:
      - "{{ .Version }}"
      - latest
    dockerfile: Dockerfile.goreleaser

changelog:
  use: git-cliff
  sort: asc
