version: 2

builds:
  - main: ./cmd/topf
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.version={{.Version}}

archives:
  - formats:
      - tar.gz
    name_template: >-
      {{ .ProjectName }}_{{ .Os }}_{{ .Arch }}

dockers_v2:
  - images:
      - ghcr.io/postfinance/topf
    tags:
      - "v{{ .Version }}"
      - latest
    dockerfile: Dockerfile.goreleaser

homebrew_casks:
  - name: topf
    binaries:
      - topf
    repository:
      owner: postfinance
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
    homepage: https://github.com/postfinance/topf
    description: Talos Orchestrator by PostFinance
    hooks:
      post:
        install: |
          if OS.mac?
            system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/topf"]
          end

changelog:
  use: github
  sort: asc
