version: "3"

tasks:
  default:
    desc: build
    vars:
      VERSION:
        sh: git describe --tags --always --dirty 2>/dev/null || echo "dev"
    cmds:
      - echo "Building topf version {{.VERSION}}..."
      - go build -ldflags "-X main.version={{.VERSION}}" -o bin/topf ./cmd/topf


  clean:
    desc: Clean build artifacts and caches
    cmds:
      - echo "Cleaning..."
      - rm -rf bin

  snapshot:
    desc: Build a local snapshot release with goreleaser
    cmds:
      - goreleaser release --snapshot --clean

  lint:
    desc: Run linter
    cmds:
      - echo "Running linter..."
      - golangci-lint run

  changelog:
    desc: Generate changelog with git-cliff
    cmds:
      - git-cliff -o CHANGELOG.md

  docs:
    desc: Serve documentation locally
    cmds:
      - mkdocs serve

