version: "3"

tasks:
  default:
    desc: build
    vars:
      VERSION:
        sh: git describe --tags --always --dirty 2>/dev/null || echo "dev"
    cmds:
      - echo "Building topf version {{.VERSION}}..."
      - go build -ldflags "-X main.version={{.VERSION}}" -o bin/topf ./cmd/topf


  clean:
    desc: Clean build artifacts and caches
    cmds:
      - echo "Cleaning..."
      - rm -rf bin

  lint:
    desc: Run linter
    cmds:
      - echo "Running linter..."
      - golangci-lint run

